// <auto-generated />

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PugnaFighting.Web.Views.Fighters
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}
