// <auto-generated />

namespace PugnaFighting.Data.Migrations
{
    using System;
    using Microsoft.EntityFrameworkCore.Migrations;
    public partial class AddCategories : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Fighters_PersonalInfo_PersonalInfoId",
                table: "Fighters");

            migrationBuilder.DropTable(
                name: "PersonalInfo");

            migrationBuilder.DropIndex(
                name: "IX_Fighters_PersonalInfoId",
                table: "Fighters");

            migrationBuilder.DropColumn(
                name: "PersonalInfoId",
                table: "Fighters");

            migrationBuilder.AddColumn<int>(
                name: "BiographyId",
                table: "Fighters",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "CategoryId",
                table: "Fighters",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateTable(
                name: "Biographies",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    CreatedOn = table.Column<DateTime>(nullable: false),
                    ModifiedOn = table.Column<DateTime>(nullable: true),
                    IsDeleted = table.Column<bool>(nullable: false),
                    DeletedOn = table.Column<DateTime>(nullable: true),
                    FirstName = table.Column<string>(maxLength: 50, nullable: false),
                    Nickname = table.Column<string>(maxLength: 50, nullable: false),
                    LastName = table.Column<string>(maxLength: 50, nullable: false),
                    Nationality = table.Column<string>(maxLength: 30, nullable: false),
                    Age = table.Column<int>(nullable: false),
                    PictureUrl = table.Column<string>(nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Biographies", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Categories",
                columns: table => new
                {
                    Id = table.Column<int>(nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    CreatedOn = table.Column<DateTime>(nullable: false),
                    ModifiedOn = table.Column<DateTime>(nullable: true),
                    IsDeleted = table.Column<bool>(nullable: false),
                    DeletedOn = table.Column<DateTime>(nullable: true),
                    Name = table.Column<string>(nullable: true),
                    WeightLimit = table.Column<string>(nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Categories", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Fighters_BiographyId",
                table: "Fighters",
                column: "BiographyId");

            migrationBuilder.CreateIndex(
                name: "IX_Fighters_CategoryId",
                table: "Fighters",
                column: "CategoryId");

            migrationBuilder.CreateIndex(
                name: "IX_Biographies_IsDeleted",
                table: "Biographies",
                column: "IsDeleted");

            migrationBuilder.CreateIndex(
                name: "IX_Categories_IsDeleted",
                table: "Categories",
                column: "IsDeleted");

            migrationBuilder.AddForeignKey(
                name: "FK_Fighters_Biographies_BiographyId",
                table: "Fighters",
                column: "BiographyId",
                principalTable: "Biographies",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_Fighters_Categories_CategoryId",
                table: "Fighters",
                column: "CategoryId",
                principalTable: "Categories",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Fighters_Biographies_BiographyId",
                table: "Fighters");

            migrationBuilder.DropForeignKey(
                name: "FK_Fighters_Categories_CategoryId",
                table: "Fighters");

            migrationBuilder.DropTable(
                name: "Biographies");

            migrationBuilder.DropTable(
                name: "Categories");

            migrationBuilder.DropIndex(
                name: "IX_Fighters_BiographyId",
                table: "Fighters");

            migrationBuilder.DropIndex(
                name: "IX_Fighters_CategoryId",
                table: "Fighters");

            migrationBuilder.DropColumn(
                name: "BiographyId",
                table: "Fighters");

            migrationBuilder.DropColumn(
                name: "CategoryId",
                table: "Fighters");

            migrationBuilder.AddColumn<int>(
                name: "PersonalInfoId",
                table: "Fighters",
                type: "int",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.CreateTable(
                name: "PersonalInfo",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Age = table.Column<int>(type: "int", nullable: false),
                    Category = table.Column<int>(type: "int", nullable: false),
                    CreatedOn = table.Column<DateTime>(type: "datetime2", nullable: false),
                    DeletedOn = table.Column<DateTime>(type: "datetime2", nullable: true),
                    FirstName = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false),
                    LastName = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    ModifiedOn = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Nationality = table.Column<string>(type: "nvarchar(30)", maxLength: 30, nullable: false),
                    Nickname = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false),
                    PictureUrl = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PersonalInfo", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Fighters_PersonalInfoId",
                table: "Fighters",
                column: "PersonalInfoId");

            migrationBuilder.CreateIndex(
                name: "IX_PersonalInfo_IsDeleted",
                table: "PersonalInfo",
                column: "IsDeleted");

            migrationBuilder.AddForeignKey(
                name: "FK_Fighters_PersonalInfo_PersonalInfoId",
                table: "Fighters",
                column: "PersonalInfoId",
                principalTable: "PersonalInfo",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
