// <auto-generated />

namespace PugnaFighting.Data.Migrations
{
    using Microsoft.EntityFrameworkCore.Migrations;

    public partial class UsersFightersCount : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
