// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace PugnaFighting.Data.Migrations
{
    public partial class RemoveTeams : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Coaches_Teams_TeamId",
                table: "Coaches");

            migrationBuilder.DropForeignKey(
                name: "FK_Fighters_AspNetUsers_ApplicationUserId",
                table: "Fighters");

            migrationBuilder.DropTable(
                name: "Teams");

            migrationBuilder.DropIndex(
                name: "IX_Fighters_ApplicationUserId",
                table: "Fighters");

            migrationBuilder.DropIndex(
                name: "IX_Coaches_TeamId",
                table: "Coaches");

            migrationBuilder.DropColumn(
                name: "Nationality",
                table: "Managers");

            migrationBuilder.DropColumn(
                name: "ApplicationUserId",
                table: "Fighters");

            migrationBuilder.DropColumn(
                name: "Nationality",
                table: "Cutmen");

            migrationBuilder.DropColumn(
                name: "Nationality",
                table: "Coaches");

            migrationBuilder.DropColumn(
                name: "TeamId",
                table: "Coaches");

            migrationBuilder.DropColumn(
                name: "Nationality",
                table: "Biographies");

            migrationBuilder.AddColumn<int>(
                name: "FansCount",
                table: "Organizations",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "InstantCash",
                table: "Organizations",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "MoneyPerFight",
                table: "Organizations",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<string>(
                name: "BornCountry",
                table: "Managers",
                maxLength: 30,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<int>(
                name: "FansCount",
                table: "Managers",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<int>(
                name: "MoneyPerFight",
                table: "Managers",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<string>(
                name: "UserId",
                table: "Fighters",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "BornCountry",
                table: "Cutmen",
                maxLength: 30,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "BornCountry",
                table: "Coaches",
                maxLength: 30,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<int>(
                name: "SkillBonus",
                table: "Coaches",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AlterColumn<string>(
                name: "PictureUrl",
                table: "Biographies",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "nvarchar(max)");

            migrationBuilder.AddColumn<string>(
                name: "BornCountry",
                table: "Biographies",
                maxLength: 30,
                nullable: false,
                defaultValue: "");

            migrationBuilder.CreateIndex(
                name: "IX_Fighters_UserId",
                table: "Fighters",
                column: "UserId");

            migrationBuilder.AddForeignKey(
                name: "FK_Fighters_AspNetUsers_UserId",
                table: "Fighters",
                column: "UserId",
                principalTable: "AspNetUsers",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Fighters_AspNetUsers_UserId",
                table: "Fighters");

            migrationBuilder.DropIndex(
                name: "IX_Fighters_UserId",
                table: "Fighters");

            migrationBuilder.DropColumn(
                name: "FansCount",
                table: "Organizations");

            migrationBuilder.DropColumn(
                name: "InstantCash",
                table: "Organizations");

            migrationBuilder.DropColumn(
                name: "MoneyPerFight",
                table: "Organizations");

            migrationBuilder.DropColumn(
                name: "BornCountry",
                table: "Managers");

            migrationBuilder.DropColumn(
                name: "FansCount",
                table: "Managers");

            migrationBuilder.DropColumn(
                name: "MoneyPerFight",
                table: "Managers");

            migrationBuilder.DropColumn(
                name: "UserId",
                table: "Fighters");

            migrationBuilder.DropColumn(
                name: "BornCountry",
                table: "Cutmen");

            migrationBuilder.DropColumn(
                name: "BornCountry",
                table: "Coaches");

            migrationBuilder.DropColumn(
                name: "SkillBonus",
                table: "Coaches");

            migrationBuilder.DropColumn(
                name: "BornCountry",
                table: "Biographies");

            migrationBuilder.AddColumn<string>(
                name: "Nationality",
                table: "Managers",
                type: "nvarchar(30)",
                maxLength: 30,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "ApplicationUserId",
                table: "Fighters",
                type: "nvarchar(450)",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Nationality",
                table: "Cutmen",
                type: "nvarchar(30)",
                maxLength: 30,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<string>(
                name: "Nationality",
                table: "Coaches",
                type: "nvarchar(30)",
                maxLength: 30,
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<int>(
                name: "TeamId",
                table: "Coaches",
                type: "int",
                nullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "PictureUrl",
                table: "Biographies",
                type: "nvarchar(max)",
                nullable: false,
                oldClrType: typeof(string),
                oldNullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Nationality",
                table: "Biographies",
                type: "nvarchar(30)",
                maxLength: 30,
                nullable: false,
                defaultValue: "");

            migrationBuilder.CreateTable(
                name: "Teams",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    CreatedOn = table.Column<DateTime>(type: "datetime2", nullable: false),
                    DeletedOn = table.Column<DateTime>(type: "datetime2", nullable: true),
                    IsDeleted = table.Column<bool>(type: "bit", nullable: false),
                    Location = table.Column<string>(type: "nvarchar(30)", maxLength: 30, nullable: false),
                    LogoUrl = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    ModifiedOn = table.Column<DateTime>(type: "datetime2", nullable: true),
                    Name = table.Column<string>(type: "nvarchar(50)", maxLength: 50, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Teams", x => x.Id);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Fighters_ApplicationUserId",
                table: "Fighters",
                column: "ApplicationUserId");

            migrationBuilder.CreateIndex(
                name: "IX_Coaches_TeamId",
                table: "Coaches",
                column: "TeamId");

            migrationBuilder.CreateIndex(
                name: "IX_Teams_IsDeleted",
                table: "Teams",
                column: "IsDeleted");

            migrationBuilder.AddForeignKey(
                name: "FK_Coaches_Teams_TeamId",
                table: "Coaches",
                column: "TeamId",
                principalTable: "Teams",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_Fighters_AspNetUsers_ApplicationUserId",
                table: "Fighters",
                column: "ApplicationUserId",
                principalTable: "AspNetUsers",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }
    }
}
